### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by pongells** [CycloneDX/cyclonedx-node-yarn#10]
Hello, is this still under development?

Thanks.

**Comment by fkluthe** [comment]
And what will be supported? Both, Yarn 1 and 2?

**Comment by jkowalleck** [comment]
this is still planned/in-dev
read about the vision here: https://github.com/CycloneDX/cyclonedx-node-yarn/discussions/8

**Comment by sbernard31** [comment]
> this is still planned/in-dev

@jkowalleck but for now there is nothing released, right ? 

Do you think something usable will be released soon OR the project is far to provide that ? 

Waiting for a yarn project which would like to generate SBOM what do you advise to use ?

**Comment by jkowalleck** [comment]
> but for now there is nothing released, right ?

right. nobody took the challenge to build this very SBOM tool.
Feel free to contribute or champion the project.

**Comment by jkowalleck** [comment]
a release candidate is ready for testing. see 
https://github.com/CycloneDX/cyclonedx-node-yarn/pull/6#issuecomment-2143002920
