### ISSUE TITLE
:mega: looking for contributors

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-node-yarn#12]
CycloneDX is a community effort, free for all.

Based on https://github.com/CycloneDX/cyclonedx-node-yarn/discussions/8
This project is currently looking for contributors/champions.

Drop a note, or ping, if you are interested.

**Comment by fkluthe** [comment]
One question regarding the direction of the community: 
Will there always be the need for language/ecosystem specific tools, or is there a shift towards the one-fits-all tool [cdxgen](https://github.com/CycloneDX/cdxgen#supported-languages-and-package-format)?

**Comment by jkowalleck** [comment]
> Will there always be the need for language/ecosystem specific tools
whatever suites best for the job.
This specific project is about creating a plugin for yarn. This way a first-citizen access to all yarn data is guaranteed and data sourcing is most accurate.

> is there a shift towards the one-fits-all tool [cdxgen](https://github.com/CycloneDX/cdxgen#supported-languages-and-package-format)?
nope. `cdxgen` is just any CycloneDX generator. Feel free to use the tools that suite you best. 
Come join the community for more questions: https://cyclonedx.org/about/participate/#communications

**Comment by sbernard31** [comment]
> Will there always be the need for language/ecosystem specific tools, or is there a shift towards the one-fits-all too

I was asking myself exactly same question.

Intuitively, I was expected to find more easily little language/ecosystem specific tools.
Because, I was thinking : 
 -  this will be easier to embrace language/ecosystem specificity. 
 - and also it should be easily for OSS community to maintain smaller project with very limited scope. 
 
 But it seems that huge tooling which do everything is more common :shrug: : 
- [Trivy](https://aquasecurity.github.io/trivy)
- [OSS Review Toolkit / ort](https://github.com/oss-review-toolkit/ort)
- [CycloneDX Generator / cdxgen](https://github.com/CycloneDX/cdxgen))

**Comment by jkowalleck** [comment]
see https://github.com/CycloneDX/cyclonedx-node-yarn/discussions/8

**Comment by sbernard31** [comment]
(Just in case it helps : https://github.com/yarnpkg/berry/discussions/6063)

**Comment by AugustusKling** [comment]
@jkowalleck I've experimented yesterday with creating a Yarn plugin to generate CycloneDX SBoMs. The generated files look good at first glance.

Note however that I don't want to make any promises just yet without doing some further assessments if the taken approach is sound. Expect some update on this in a couple of days.

**Comment by AugustusKling** [comment]
@jkowalleck, @sbernard31 see draft in PR #13. This plugin generates correctly looking SBOMs for the projects I've tested with as far as I can judge.

Easiest way to test on existing Yarn projects is `yarn plugin import https://raw.githubusercontent.com/AugustusKling/cyclonedx-node-yarn/1.0-dev/bundles/%40yarnpkg/plugin-sbom.js` followed by `yarn sbom --component-type=application --output-file=sbom.cdx.json` if you want to trust minified code by a random guy.

The more sensible way is:

1. Checkout the repo.
2. `yarn install`
3. Carefully check source code.
4. Build using `yarn build` or `yarn build:dev`
5. Change to your project directory.
6. Import plugin `yarn plugin import /wherever-your-checkout-is/bundles/@yarnpkg/plugin-sbom.js`
7. `yarn sbom --component-type=application --output-file=sbom.cdx.json`

**Comment by jkowalleck** [comment]
Implementation is coming to an end, nearly all features are done.
closing issue
