### ISSUE TITLE
[ValidationError] Depricated CycloneDX format is used

### ISSUE THREAD

**Issue by Lasitrox** [CycloneDX/cyclonedx-node-yarn#158]
## Summary

CycloneDX protocoll versions 1.5 and 1.6 use this depricated format:
https://cyclonedx.org/docs/1.6/json/#tab-pane_metadata_tools_oneOf_i1 

## To Reproduce

1. How was _@cyclonedx/yarn-plugin-cyclonedx_  called?
   yarn exec cyclonedx-yarn --prod --spec-version 1.6 --output-format JSON --output-file sbom-frontend-code-1.0.0-rc3.cyclonedx.json
2. What kind of evidence was processed?
   I tried to use [sbom2doc](https://github.com/anthonyharrison/sbom2doc) but in crashed.
   For 1.5 and 1.6 the tool expects the new format but the deprecated one is used

## Environment

- @cyclonedx/yarn-plugin-cyclonedx v1.0.1+git.af49afc
- 4.3.1
- v20.9.0
- Windows 10

**Comment by jkowalleck** [comment]
> 2\. I tried to use [sbom2doc](https://github.com/anthonyharrison/sbom2doc) but in crashed.
>         For 1.5 and 1.6 the tool expects the new format but the deprecated one is used

you should report the issue to the authors of sbom2doc :D

**Comment by jkowalleck** [comment]
@anthonyharrison FYI

**Comment by anthonyharrison** [comment]
> @anthonyharrison FYI

@Lasitrox If you use the latest working version of [lib4sbom](https://github.com/anthonyharrison/lib4sbom) (it will become version 0.7.2 when I finish some updates) and the latest sbom2doc, it should work. I have only been able to try it on a very simple yarn project (I installed webpack-dev-server to get lots of dependencies!)

The default version of Cycl;oneDX is 1.6. However you can force the version of CycloneDX by setting the environment variable LIB4SBOM_CYCLONEDX_VERSION to the version e.g. 1.5

Many of the tools have not yet been upgraded to use the non-deprecated version of the metadata when producing version 1.6 SBOMs (this is reported if the environment variable LIB4SBOM_DEBUG is set to 1)

cc @jkowalleck

**Comment by jkowalleck** [comment]
@anthonyharrison 

> Many of the tools have not yet been upgraded to use the non-deprecated version of the metadata when producing version 1.6 SBOMs

And some probably never will be.
The data model "Tool" is still valid in CycloneDX >= 1.5 and ingesting tools must support it.



> The default version of Cycl;oneDX is 1.6. [...]

is there no schema-validation and version-detection in your tool, so that the appropriate behaviour is chosen?

**Comment by anthonyharrison** [comment]
> @anthonyharrison
> 
> > Many of the tools have not yet been upgraded to use the non-deprecated version of the metadata when producing version 1.6 SBOMs
> 
> And some probably never will be. The data model "Tool" is still valid in CycloneDX `>=1.5, <2` and ingesting tools must support it.

Noted. 

> 
> > The default version of Cycl;oneDX is 1.6. [...]
> 
> is there no schema-validation and version-detection in your tool, so that the appropriate behaviour is chosen?

There is some validation so the correct behaviour can be chosen. It just needs improving :-)

**Comment by Lasitrox** [comment]
@anthonyharrison thank you.
I will be looking for the changes.
