### ISSUE TITLE
CHORE: omit installation of unused, transitive optional dependencies

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-node-yarn#218]
some transitive dependnecies are optional, the underlying features are not used; this project's tree shaking mechanismswere optimized to not include traces of them in the final build result.
this means: it is safe to ignore them on installation.

this is especially needed, in cases where the install fails. see https://github.com/CycloneDX/cyclonedx-node-yarn/pull/193#issuecomment-2463069881 ff 

see also: https://github.com/CycloneDX/cyclonedx-javascript-library?tab=readme-ov-file#optional-dependencies

goal: do not install the following  transitive optional dependencies:
- `libxmljs2`
- `ajv`, `ajv-formats`, `ajv-formats-draft2019`

**Comment by jkowalleck** [comment]
@AugustusKling , 

I will work on this. I remember there was a thing for that in yarn package manifest, something to override and modify transitive dependencies.

**Comment by AugustusKling** [comment]
In case you are thinking about https://yarnpkg.com/configuration/yarnrc#packageExtensions, this won't help you as it can only add missing dependencies but not remove existing ones. There's also https://yarnpkg.com/configuration/manifest#resolutions which to my knowledge also does not support removal.

**Comment by jkowalleck** [comment]
i am not planning on removing them, but overriding their "version" (resolution) to target a local package that is installable, and simply throws an error as soon as it is loaded. 😁

**Comment by jkowalleck** [comment]
https://github.com/CycloneDX/cyclonedx-node-yarn/pull/219#issuecomment-2476882155 
> tests show that the optional deps are not needed on compile time, but are required for some validation during tests.
