### ISSUE TITLE
[Question] When will the next release be created?

### ISSUE THREAD

**Issue by geigervlad** [CycloneDX/cyclonedx-node-yarn#236]
### Description

First of, thanks alot for all the effort put in within this project!

I would like to use the licence texts feature and would love to have a release for this. 
For this purpose, when is the next release planned?

Thanks a lot!

**Comment by jkowalleck** [comment]
> when is the next release planned?

mid of January 2025.

**Comment by jkowalleck** [comment]
release planned for early next week

**Comment by jkowalleck** [comment]
resolved via https://github.com/CycloneDX/cyclonedx-node-yarn/releases/tag/v1.1.0 
on 2025-02-14
